<a href="https://colab.research.google.com/github/krishnathombre/Credit-card-fraud-detection-ML/blob/main/credit_card_fraud_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
#loading the dataset
data = pd.read_csv('/creditcard.csv')
#split into depenent and independent variables
x=data.drop('Class',axis=1)
y=data['Class']
#splitting into train and test sets
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=41)
#standardize features
scaler= StandardScaler()
x_train= scaler.fit_transform(x_train)
x_test= scaler.fit_transform(x_test)
#training a logistic regression model
model= LogisticRegression(max_iter=1000, random_state=41)
model.fit(x_train, y_train)
#preduiction on test set
y_pred= model.predict(x_test)
print(y_pred)
#evaluation of model
confusion_matrix= confusion_matrix(y_test,y_pred)
classification_report= classification_report(y_test,y_pred)
print(confusion_matrix)
print(classification_report)

#sample prediction
sample_feature_value= np.array([[150000,-2.15484895456456, 1.54648484835842,0.156484848453287,-0.865615445153798,2.92548454543875,-0.012387915423601,2.36554789123654,1.01233698754215,-2.115498439874521,2.13654897542154,3.21563254123654,1.23654897412536,-1.23564789641235, 3.31878995683987,0.876549821315489,0.123457891231231,-0.789123456789123,0.301254123012365,-0.144489486981235,1.23879549321456,-0.212312312312312,2.9123111123123,-1.39789654123365,1.91231231231231,-1.01231569487514,0.002315212364987,-2.123654523192315,-0.223698745214523, 99.99]])
#preprocessing of sample feature
sample_feature_value_scaled= scaler.transform(sample_feature_value)
prediction= model.predict(sample_feature_value_scaled)
print(prediction)





[0 0 0 ... 0 0 0]
[[56856    12]
 [   38    56]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56868
           1       0.82      0.60      0.69        94

    accuracy                           1.00     56962
   macro avg       0.91      0.80      0.85     56962
weighted avg       1.00      1.00      1.00     56962

[0]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


Using Random Forest model

1. Importing libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

   2. Loading the dataset

In [2]:
data = pd.read_csv("creditcard.csv")

3. splitting the dataset into dependent and independent variables

In [3]:
x= data.drop('Class', axis=1)
y= data['Class']

4. spliting the dataset into train and test set

In [4]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.15, random_state=42)

5. creating a randomforestclassifier model

In [5]:
clf = RandomForestClassifier(n_estimators=100, random_state=42)


6. training the model on dataset

In [7]:
clf.fit(x_train,y_train)

RandomForestClassifier(random_state=42)

7. prediction on the test set

In [9]:
y_pred= clf.predict(x_test)


8. Evaluation of model

In [10]:
confusion_matrix= confusion_matrix(y_test,y_pred)
classification_report=classification_report(y_test,y_pred)
print(confusion_matrix)
print(classification_report)


[[42647     1]
 [   18    56]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     42648
           1       0.98      0.76      0.85        74

    accuracy                           1.00     42722
   macro avg       0.99      0.88      0.93     42722
weighted avg       1.00      1.00      1.00     42722

